image:
  tag: "v0.14.0"
  pullPolicy: IfNotPresent

serviceAccount:
  name: "external-dns"

logLevel: debug
interval: 15s

provider: pihole
env:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-admin
        key: password

extraArgs:
- --pihole-server=http://pihole-web.pihole.svc
