---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr
  namespace: sonarr
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
