# postgres-password: PASSWORD GOES HERE 
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr-config
  namespace: prowlarr
spec:
  target:
    name: prowlarr-config
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        config.xml: |-
          {{ .config }}
  data:
    - secretKey: config
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: prowlarr-config
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres
  namespace: prowlarr
spec:
  target:
    name: postgres
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        key: 0064f5a8-f291-4b3c-9677-18d2b5073435 
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: username
      remoteRef:
        key: 0064f5a8-f291-4b3c-9677-18d2b5073435
        property: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
