# postgres-password: PASSWORD GOES HERE 
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr-config
  namespace: prowlarr
spec:
  target:
    name: prowlarr-config
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        config.xml: |-
          {{ .config }}
  data:
    - secretKey: config
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: prowlarr-config
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres
  namespace: prowlarr
spec:
  target:
    name: postgres
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        key: 61a4c223-1fe5-4228-9ee1-0e0d057dd997
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: username
      remoteRef:
        key: 61a4c223-1fe5-4228-9ee1-0e0d057dd997
        property: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
