---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
