apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs
  namespace: nfs
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
  template:
    spec:
      serviceAccountName: nfs-subdir-external-provisioner
      containers:
        - name: nfs-subdir-external-provisioner
          image: "registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-subdir-external-provisioner-root
              mountPath: /persistentvolumes
          envFrom:
            - configMapRef:
                name: nfs-config
      volumes:
        - name: nfs-subdir-external-provisioner-root
          nfs:
            server: 127.0.0.1
            path: /nfs/path
