apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfs

commonLabels:
  app: nfs-subdir-external-provisioner

resources:
  - namespace.yaml
  - rbac.yaml
  - service-account.yaml
  - deployment.yaml
  - storage-class.yaml
