---
apiVersion: v1
kind: Namespace
metadata:
  name: plex
---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app: plex-media-server
    app.kubernetes.io/name: plex-media-server
    app.kubernetes.io/version: 1.16.0
  name: plex-media-server
  namespace: plex
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: plex-media-server
    app.kubernetes.io/name: plex-media-server
  name: plex-media-server
  namespace: plex
spec:
  ports:
  - name: pms
    port: 32400
    protocol: TCP
    targetPort: 32400
  selector:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex-media-server
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-server
  namespace: plex
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-retain
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: plex-media-server
    app.kubernetes.io/name: plex-media-server
    name: plex-media-server
  name: plex-media-server
  namespace: plex
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: plex
      app.kubernetes.io/name: plex-media-server
  template:
    metadata:
      labels:
        app: plex-media-server
        app.kubernetes.io/name: plex-media-server
    spec:
      hostNetwork: true
      affinity: {}
      containers:
      - env:
        - name: ALLOWED_NETWORKS
          value: 0.0.0.0/0.0.0.0
        - name: PLEX_CLAIM
          value: CLAIMGOESHERE
        - name: TZ
          value: America/Detroit
        image: index.docker.io/plexinc/pms-docker:1.32.8.7639-fb6452ebf
        imagePullPolicy: IfNotPresent
        name: plex-media-server-pms
        ports:
        - containerPort: 32400
          name: pms
        volumeMounts:
        - mountPath: /config
          name: pms-config
        - mountPath: /transcode
          name: pms-transcode
        - mountPath: /media
          name: media
        - mountPath: /critical_media
          name: critical-media
        resources: 
          requests: 
              gpu.intel.com/i915: "1" 
          limits: 
              gpu.intel.com/i915: "1" 
      initContainers: null
      nodeSelector: {}
      serviceAccountName: plex-media-server
      terminationGracePeriodSeconds: 120
      tolerations: []
      volumes:
      - name: pms-transcode
        emptyDir: {}
      - name: pms-config
        persistentVolumeClaim:
          claimName: plex-media-server
      - name: media
        nfs:
          path: /volume1/media
          readOnly: true
          server: nas01.crt.house
      - name: critical-media
        nfs:
          path: /volume1/critical/media
          readOnly: true
          server: nas01.crt.house
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: plex.crt.house
    external-dns.alpha.kubernetes.io/target: crt.house
  labels:
    app: plex-media-server
    name: plex-media-server-ingress
  name: plex-media-server-ingress
  namespace: plex
spec:
  ingressClassName: nginx-external
  rules:
  - host: plex.crt.house
    http:
      paths:
      - backend:
          service:
            name: plex-media-server
            port:
              number: 32400
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - plex.crt.house
    secretName: crt.house
