extraConfigmapMounts:
  - name: etc-dashboards
    mountPath: /etc/dashboards
    configMap: etc-dashboards
    readOnly: true

annotations:
  reloader.stakater.com/auto: "true"

service:
  port: 80
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-crt-house
    external-dns.alpha.kubernetes.io/hostname: grafana.crt.house
    nginx.org/websocket-services: grafana
  path: /
  pathType: Prefix
  hosts:
    - grafana.crt.house
  tls:
    - hosts:
        - grafana.crt.house

persistence:
  type: pvc
  enabled: true
  storageClassName: longhorn

admin:
  existingSecret: "grafana"

envValueFrom:
  INFLUX_TOKEN:
    secretKeyRef:
      name: influxdb-auth
      key: admin-token

datasources:
 datasources.yaml:
  apiVersion: 1
  datasources:
  - name: influxdb2
    type: influxdb
    access: proxy
    url: http://influxdb2.influxdb2.svc:8086
    jsonData:
      defaultBucket: telegraf
      organization: influxdata
      tlsSkipVerify: true
      version: Flux
    secureJsonData:
      token: $INFLUX_TOKEN
  - name: loki
    type: loki
    access: proxy
    url: http://loki.loki.svc:3100
    jsonData:
      tlsSkipVerify: true


dashboardProviders:
 dashboardproviders.yaml:
   apiVersion: 1
   providers:
   - name: 'default'
     orgId: 1
     folder: ''
     type: file
     disableDeletion: false
     editable: true
     options:
       path: /etc/dashboards

namespaceOverride: "grafana"
