---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-script
  namespace: rsync-seedbox
data:
  sync.sh: |-
    #!/bin/sh
    mkdir /root/.ssh
    cp -v /ssh/* /root/.ssh
    chmod -R 600 /root/.ssh
    rsync --compress --delete-after --recursive --size-only --verbose seedbox:downloads/complete/ /complete/
