---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rsync-seedbox

commonLabels:
  app: rsync-seedbox

resources:
  - namespace.yaml
  - configmap.yaml
  - external-secret.yaml
  - cronjob.yaml
