---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole
  namespace: pihole
spec:
  target:
    name: pihole-admin
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        key: d9a69115-1c2f-4193-86df-96db05f5abf2
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
