image:
  repository: eclipse-mosquitto
  tag: 2.0.18@sha256:fa9822d3e9bdb12c80f6cb7ddd22922b26c1cd4ffa071815242ac156f9559d7d
  pullPolicy: IfNotPresent

service:
  main:
    type: ClusterIP

  websockets:
    enabled: false

persistence:
  data:
    enabled: false
  configinc:
    enabled: false

  mosquitto-config:
    enabled: true
    mountPath: "/mosquitto/config/mosquitto.conf"
    subPath: "mosquitto.conf"
    type: configmap
    objectName: config
