---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: home-assistant
data:
  configuration.yaml: |
    default_config:

    http:
      use_x_forwarded_for: true
      trusted_proxies:
      - 192.168.1.0/24
      - 10.42.0.0/16

    homeassistant:
      name: 337
      latitude: !env_var LATITUDE
      longitude: !env_var LONGITUDE
      elevation: 709
      unit_system: imperial
      time_zone: America/Detroit

    automation: !include automations.yaml


