---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: home-assistant
data:
  configuration.yaml: |
    default_config:

    http:
      use_x_forwarded_for: true
      trusted_proxies:
      - 192.168.1.0/24
      - 10.42.0.0/16

    homeassistant:
      name: 337
      latitude: 42.97
      longitude: -85.68
      elevation: 709
      unit_system: imperial
      time_zone: America/Detroit
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  type: ClusterIP
  ports:
  - port: 8123
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: home-assistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/instance: home-assistant
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: home-assistant
          image: "ghcr.io/home-assistant/home-assistant:2023.12.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Detroit
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          volumeMounts:
          - mountPath: /config
            name: config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: home-assistant
      - configMap:
          name: config
        name: configmap
      hostNetwork: true
      initContainers:
      - command:
        - /bin/sh
        - -c
        - ' cp -v /configmap/*.yaml /config/'
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        name: copy
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /configmap/
          name: configmap
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ass.crt.house
    external-dns.alpha.kubernetes.io/target: crt.house
    nginx.org/websocket-services: home-assistant
spec:
  ingressClassName: crt-house-external
  tls:
    - hosts:
      - ass.crt.house
  rules:
    - host: "ass.crt.house"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
