---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: grafana
spec:
  target:
    name: grafana
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        admin-password: |-
          {{ .password }}
        admin-user: |-
          {{ .username }}
  data:
    - secretKey: password
      remoteRef:
        key: e05f9e8d-a964-4d5f-b890-9f4b27148921
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: username
      remoteRef:
        key: e05f9e8d-a964-4d5f-b890-9f4b27148921
        property: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influxdb-auth
  namespace: grafana
spec:
  target:
    name: influxdb-auth
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        admin-password: |-
          {{ .password }}
        admin-token: |-
          {{ .token }}
  data:
    - secretKey: password
      remoteRef:
        key: 662b50fe-be2e-4e7b-9bad-8ee37a7c51e1
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: token
      remoteRef:
        key: 662b50fe-be2e-4e7b-9bad-8ee37a7c51e1
        property: admin-token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
