apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radarr

commonLabels:
  app: radarr

resources:
  - backups.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - pvc.yaml
  - service.yaml
