---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr
  namespace: radarr
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
