---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  target:
    name: home-assistant
    deletionPolicy: Delete
  dataFrom:
    - sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      extract:
        key: home-assistant
