---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  type: ClusterIP
  ports:
  - port: 8123
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: home-assistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/instance: home-assistant
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: home-assistant
          image: "ghcr.io/home-assistant/home-assistant:2023.12.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Detroit
            - name: LATITUDE
              valueFrom:
                secretKeyRef:
                  name: home-assistant
                  key: latitude
            - name: LONGITUDE
              valueFrom:
                secretKeyRef:
                  name: home-assistant
                  key: longitude
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          volumeMounts:
          - mountPath: /config
            name: config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: home-assistant
      - configMap:
          name: configuration-yaml
        name: configuration-yaml
      - configMap:
          name: automations-yaml
        name: automations-yaml
      hostNetwork: true
      initContainers:
      - name: copy
        command:
        - /bin/sh
        - -c
        - ' cp -v /configuration-yaml/configuration.yaml /automations-yaml/automations.yaml /config/'
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /configuration-yaml/
          name: configuration-yaml
        - mountPath: /automations-yaml/
          name: automations-yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ass.crt.house
    external-dns.alpha.kubernetes.io/target: crt.house
    nginx.org/websocket-services: home-assistant
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
      - ass.crt.house
      secretName: crt.house
  rules:
    - host: "ass.crt.house"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
