alias: CT Bath Switch Off
description: ""
trigger:
  - platform: device
    domain: mqtt
    device_id: ebbf7666850a5a664a9675d49cc270b7
    type: action
    subtype: off_press_release
    discovery_id: 0x001788010c29e807 action_off_press_release
  - platform: device
    domain: mqtt
    device_id: ebbf7666850a5a664a9675d49cc270b7
    type: action
    subtype: off_press
    discovery_id: 0x001788010c29e807 action_off_press
condition: []
action:
  - type: turn_off
    device_id: 05db9b5d8b33e6d69d61e0c3f10097d2
    entity_id: cdf1e1e3d57d631d90df24dd66f10f62
    domain: light
  - type: turn_off
    device_id: cf13b868bb8a1a584e068d0d53696471
    entity_id: d7ab22d757c625e844ddd57ed7844b7a
    domain: light
  - type: turn_off
    device_id: 4251f1ff975d7308138c51e433cb3c20
    entity_id: 1e22633599370136c48f4612f13cbf74
    domain: light
mode: single
