alias: CT Bedroom Switch On
description: ""
trigger:
  - platform: device
    domain: mqtt
    device_id: 56f9d0be4d86c1025c9e9b971fdcbcf3
    type: action
    subtype: on_press
    discovery_id: 0x001788010b7457e4 action_on_press
  - platform: device
    domain: mqtt
    device_id: 56f9d0be4d86c1025c9e9b971fdcbcf3
    type: action
    subtype: on_press_release
    discovery_id: 0x001788010b7457e4 action_on_press_release
condition: []
action:
  - type: turn_on
    device_id: 86947dc3993b59bc2a428d4fd8b90fde
    entity_id: a7b7086e644289db071ea71a9a9fc2a2
    domain: light
mode: single
