---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  target:
    name: argocd-secret
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        admin.password: |-
          {{ .password }}
  data:
    - secretKey: password
      remoteRef:
        key: 58ab6e10-c731-484c-9ce2-d8be006cae65
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
