apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

commonLabels:
  app: argocd

resources:
  - configmap.yaml
  - crd.yaml
  - deployment.yaml
  - external-secret.yaml
  - ingress.yaml
  - namespace.yaml
  - network-policy.yaml
  - rbac.yaml
  - secret.yaml
  - service.yaml
  - service-account.yaml
  - stateful-set.yaml
