image:
  tag: "2023.11.0"
  pullPolicy: IfNotPresent

serviceDns:
  type: LoadBalancer
  # ExternalTrafficPolicy: Cluster
  mixedService: true
  annotations:
    metallb.universe.tf/address-pool: dns

serviceDhcp:
  # -- Generate a Service resource for DHCP traffic
  enabled: false

serviceWeb:
  http:
    enabled: true
  https:
    enabled: true

virtualHost: pihole.crt.house

# -- Configuration for the Ingress
ingress:
  # -- Generate a Ingress resource
  enabled: true

  # -- Specify an ingressClassName
  ingressClassName: nginx-crt-house

  annotations:
    external-dns.alpha.kubernetes.io/hostname: pihole.crt.house

  path: /
  hosts:
    - pihole.crt.house
  tls:
  - hosts:
    - pihole.crt.house

persistentVolumeClaim:
  enabled: true
  # existingClaim: "pihole"
  accessModes:
    - ReadWriteOnce
  size: "500Mi"
  storageClass: "longhorn"

admin:
  existingSecret: "pihole-admin"
  passwordKey: "password"

extraEnvVars:
  TZ: America/Detroit

DNS1: "1.1.1.1"
DNS2: "8.8.8.8"

dnsmasq:
  # -- Add upstream dns servers. All lines will be added to the pihole dnsmasq configuration
  upstreamServers: []
  # - server=/foo.bar/192.168.178.10
  # - server=/bar.foo/192.168.178.11

  # -- Add custom dns entries to override the dns resolution. All lines will be added to the pihole dnsmasq configuration.
  customDnsEntries: []
  # - address=/foo.bar/192.168.178.10
  # - address=/bar.foo/192.168.178.11

  # -- Dnsmasq reads the /etc/hosts file to resolve ips. You can add additional entries if you like
  additionalHostsEntries: []
  # - 192.168.0.3     host4
  # - 192.168.0.4     host5

  # -- Other options
  customSettings:
  # otherSettings:
  # - rebind-domain-ok=/plex.direct/

  # -- Here we specify custom cname entries that should point to `A` records or
  # elements in customDnsEntries array.
  # The format should be:
  #  - cname=cname.foo.bar,foo.bar
  #  - cname=cname.bar.foo,bar.foo
  #  - cname=cname record,dns record
  customCnameEntries: []
  # Here we specify custom cname entries that should point to `A` records or
  # elements in customDnsEntries array.
  # The format should be:
  #   - cname=cname.foo.bar,foo.bar
  #   - cname=cname.bar.foo,bar.foo
  #   - cname=cname record,dns record

# -- list of adlists to import during initial start of the container
adlists:
  {}
  # If you want to provide blocklists, add them here.
  # - https://hosts-file.net/grm.txt
  # - https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts

hostname: "pihole"
podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
    - 127.0.0.1
    - 1.1.1.1
    - 8.8.8.8
