---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crt.lol
  namespace: nginx-crt-lol
spec:
  secretName: crt.lol
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: "*.crt.lol"
  dnsNames:
    - "*.crt.lol"
