apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metube

commonLabels:
  app: metube

resources:
  - deployment.yaml
  - external-secret.yaml
  - ingress.yaml
  - namespace.yaml
  - service.yaml
