---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole
  namespace: external-dns
spec:
  target:
    name: pihole-admin
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        key: d9a69115-1c2f-4193-86df-96db05f5abf2
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: external-dns
spec:
  target:
    name: cloudflare
    deletionPolicy: Delete
  data:
    - secretKey: api-key
      remoteRef:
        key: add0d418-949a-4bda-b535-52055706665e
        property: api-key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
