---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  target:
    name: zigbee2mqtt
    deletionPolicy: Delete
  dataFrom:
    - sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      extract:
        key: zigbee2mqtt-json
