---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influxdb-auth
  namespace: telegraf
spec:
  target:
    name: influxdb-auth
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        admin-password: |-
          {{ .password }}
        admin-token: |-
          {{ .token }}
  data:
    - secretKey: password
      remoteRef:
        key: 662b50fe-be2e-4e7b-9bad-8ee37a7c51e1
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: token
      remoteRef:
        key: 662b50fe-be2e-4e7b-9bad-8ee37a7c51e1
        property: admin-token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
