image:
  repository: registry.k8s.io/nfd/node-feature-discovery
  pullPolicy: IfNotPresent
  tag: v0.14.3-minimal

nameOverride: ""
fullnameOverride: ""
namespaceOverride: "nfd"

master:
  serviceAccount:
    create: true
    name: nfd-master

worker:
  config:
    sources:
      usb:
        deviceClassWhiteList:
          - "02"
          - "0e"
          - "ef"
          - "fe"
          - "ff"

  serviceAccount:
    create: true
    name: nfd-worker

  # Allow users to mount the hostPath /usr/src, useful for RHCOS on s390x
  # Does not work on systems without /usr/src AND a read-only /usr, such as Talos
  mountUsrSrc: false

topologyUpdater:
  enable: true
  createCRDs: true

  serviceAccount:
    create: true
    name: nfd-topology-updater

  updateInterval: 1m

gc:
  enable: true
  serviceAccount:
    create: true
    name: nfd-gc

prometheus:
  enable: false
  labels: {}
