---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
  annotations:
    secret.reloader.stakater.com/reload: "cloudflare"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ch@rlesthom.as

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    solvers:
    - selector:
        dnsNames:
        - "*.crt.house"
        - "*.crt.lol"
      dns01:
        cloudflare:
          email: ch@rlesthom.as
          apiTokenSecretRef:
            name: cloudflare
            key: api-key

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
  annotations:
    secret.reloader.stakater.com/reload: "cloudflare"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ch@rlesthom.as

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production

    solvers:
    - selector:
        dnsNames:
        - "*.crt.house"
        - "*.crt.lol"
      dns01:
        cloudflare:
          email: ch@rlesthom.as
          apiTokenSecretRef:
            name: cloudflare
            key: api-key
