---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  target:
    name: cloudflare
    deletionPolicy: Delete
  data:
    - secretKey: api-key
      remoteRef:
        key: d013cdc1-f4ab-4fc8-9e66-f373d2f2b069
        property: api-key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
