---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-auth
  namespace: offsite-backups
spec:
  target:
    name: tailscale-auth
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        TS_AUTHKEY: |-
          {{ .tskey }}
  data:
    - secretKey: tskey
      remoteRef:
        key: 0d01c153-f8f5-4012-8dbe-4b975be588a1
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh
  namespace: offsite-backups
spec:
  target:
    name: ssh
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        config: |-
          {{ .config }}
        id_rsa: |-
          {{ .key }}
        known_hosts: |-
          {{ .hosts }}
  data:
    - secretKey: config
      remoteRef:
        key: nas02-ssh-config
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
    - secretKey: key
      remoteRef:
        key: nas02-id_rsa
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
    - secretKey: hosts
      remoteRef:
        key: nas02-known-hosts
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
