---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: offsite-backups

commonLabels:
  app: offsite-backups

resources:
  - namespace.yaml
  - configmap.yaml
  - external-secret.yaml
  - rbac.yaml
  - cronjob.yaml
