alias: Guest Bathroom Switch On
description: ""
trigger:
  - platform: device
    domain: mqtt
    device_id: aa8bd2377193b7d83ff6f4f95aa26123
    type: action
    subtype: on-press
    discovery_id: 0x0017880102d4519a action_on-press
condition: []
action:
  - type: turn_on
    device_id: bf83e270293f87aed81d5e4803afe4ab
    entity_id: 569bfa5736db521ed3e996132075bc9a
    domain: light
  - type: turn_on
    device_id: fa4bba6fd8a65f4809b4478988b7438d
    entity_id: f27e48812678ac93479ec82b9d269433
    domain: light
  - type: turn_on
    device_id: 12911c98dfa17da0ca1355fddb794804
    entity_id: 05bc316c1cf4b0faa6124d29cfbda14c
    domain: light
mode: single
