alias: Movie Mode Enabled
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.movie_mode
    from: "off"
    to: "on"
condition: []
action:
  - type: turn_on
    device_id: 3c59d3807cd1590efa9ae3e4fa50005e
    entity_id: a9685fb2644a46c987ec327cdcf5cda0
    domain: light
    brightness_pct: 70
  - type: turn_on
    device_id: 2f15920001aa4cf4526dcd2c4ae1d0ba
    entity_id: 8e4421aade2af8343bd3d371ba88a936
    domain: light
    brightness_pct: 70
  - type: turn_on
    device_id: 1f109e1760410aa39a48145d1b471736
    entity_id: 3d4ab3fe3cf9d4eb834772c652a3d8c7
    domain: light
    brightness_pct: 70
  - type: turn_on
    device_id: 675b724b9e45751d6a48f648fd0514d1
    entity_id: d8d7623052a3f9bbfbc870c9d04d3655
    domain: light
    brightness_pct: 70
  - type: turn_on
    device_id: bdf7c3cd7590d89e31f8eb54753a6de6
    entity_id: c24f570a5d97fec3e38c53dcc3a8e248
    domain: switch
mode: single
