alias: Movie Mode Reset
description: ""
trigger:
  - platform: time
    at: "05:00:00"
condition: []
action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.movie_mode
    data: {}
mode: single
