alias: RT Bedroom Aquara Toggle On
description: When the lights are off, turn them on
trigger:
  - platform: device
    domain: mqtt
    device_id: d93b5dc09f1b98a5c9cf113aad9b74bd
    type: action
    subtype: single
    discovery_id: 0x00158d000abd3612 action_single
condition:
  - condition: state
    entity_id: input_boolean.ryan_s_bedroom_desired_lights_state
    state: "off"
action:
  - type: turn_on
    device_id: da5ccd6c274cb494855e3ba9297fcd9a
    entity_id: c034246912e3b649657d8c1b6055f745
    domain: light
  - type: turn_on
    device_id: 558582e047f320a6de70f930dd61f8df
    entity_id: 1c27f2ad7006f56bfe2f57be7492ef72
    domain: light
  - service: input_boolean.turn_on
    target:
      entity_id:
        - input_boolean.ryan_s_bedroom_desired_lights_state
      device_id: []
      area_id: []
    data: {}
mode: single
